#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# BUILD YARN DEPENDENCIES
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app npm install serve
	ynh_hide_warnings ynh_exec_as_app npm install
    ynh_hide_warnings ynh_exec_as_app npx vite build --base=$path
    ynh_hide_warnings ynh_exec_as_app npm cache clean --force
popd

# Adapt default path_url
ynh_replace --match="base: '/secretsanta/'," --replace="base: '$path'," --file="$install_dir/vite.config.ts"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
